version: '3'
services:
  web:
    build:
      context: .
      dockerfile: "environment/web/Dockerfile"
    ports:
      - "8010:80"
    volumes:
     - .:/code:delegated
    networks:
      - hub-net
  db:
    image: "mysql:5.7"
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-dev}"
      MYSQL_DATABASE: "${DB_DATABASE:-property_logic}"
      MYSQL_USER: "${DB_USERNAME:-property_logic}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-dev}"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
      - hub-net
  db_core:
    image: "mysql:5.7"
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD_CORE:-dev}"
      MYSQL_DATABASE: "${DB_DATABASE_CORE:-property_logic}"
      MYSQL_USER: "${DB_USERNAME_CORE:-referrals}"
      MYSQL_PASSWORD: "${DB_PASSWORD_CORE:-dev}"
    volumes:
     - mysqldata_core:/var/lib/mysql
    networks:
      - hub-net
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    volumes:
     - redisdata:/data
    networks:
      - hub-net
networks:
  hub-net:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
  mysqldata_core:
    driver: "local"
  redisdata:
    driver: "local"
